export const FABRICANTES = [
  "APOLO ROLAMENTOS", "BORFLEX", "BSB ROLAMENTOS", "COELBRA ELASTÔMEROS",
  "DELAIKA", "DJ INDUSTRIA", "ELASTOPUR (NN)", "GENERAL WIRING DO BRASIL",
  "GUARU", "IRPEEL", "JEPAFLEX", "MMS CARTHUR", "MOBENSANI", "PARTNERS",
  "PASIAL", "PRIME", "REPLABOR", "RHEFYLL", "RUBBER GATTI", "SAMPEL",
  "SD COIFA HOMOCINÉTICA", "SIFOBOR", "UREPOL", "WORLD FLEX",
  "ZUFER TECNOLOGIA E FERRAMENTARIA LTDA"
];
